version: '3'
services:
  davinci:
    restart: always
    container_name: davincispringboot
    image: yangxiaodong/davinci:latest
    environment:
      MYSQL_URL: jdbc:mysql://192.168.3.3:3306/davinci0.3?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true
      MYSQL_USERNAME: root
      MYSQL_PAASWORD: root
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:5.6
    restart: always
    environment :
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: davinci0.3
      MYSQL_ROOT_HOST: "%"
      DAVINCI3_HOME: /root/davinci-boot
    ports:
      - "3306:3306"
    volumes:
      - ./bin/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - davincis-db-volume:/var/lib/mysql
      - ./bin:/root/davinci-boot/bin

volumes:
  davincis-db-volume: