version: '3'
services:
#  davinci:
#    restart: always
#    container_name: davincispringboot
#    image: yangxiaodong/davinci:latest
#    ports:
#      - "8081:8081"
#    depends_on:
#      - mysql-db

  mysql-db:
    image: mysql:5.6
    restart: always
    environment :
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      DAVINCI3_HOME:~/davinci-boot
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: davinci0.3
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - ./bin/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - davincis-db-volume:/var/lib/mysql
      - ./bin:~/davinci-boot/bin

volumes:
  davincis-db-volume: